// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: domain.proto

/*
Package go_micro_srv_automation is a generated protocol buffer package.

It is generated from these files:
	domain.proto

It has these top-level messages:
	Request
	Response
*/
package go_micro_srv_automation

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "context"

	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Domain service

type DomainService interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
}

type domainService struct {
	c    client.Client
	name string
}

func NewDomainService(name string, c client.Client) DomainService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "go.micro.srv.automation"
	}
	return &domainService{
		c:    c,
		name: name,
	}
}

func (c *domainService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Domain.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Domain service

type DomainHandler interface {
	Call(context.Context, *Request, *Response) error
}

func RegisterDomainHandler(s server.Server, hdlr DomainHandler, opts ...server.HandlerOption) {
	type domain interface {
		Call(ctx context.Context, in *Request, out *Response) error
	}
	type Domain struct {
		domain
	}
	h := &domainHandler{hdlr}
	s.Handle(s.NewHandler(&Domain{h}, opts...))
}

type domainHandler struct {
	DomainHandler
}

func (h *domainHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.DomainHandler.Call(ctx, in, out)
}
